name: Linux-RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 4320

    steps:
      - name: Install XFCE Desktop & xRDP
        run: |
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies xrdp
          sudo systemctl enable xrdp
          sudo systemctl start xrdp

      - name: Create RDP User with Secure Password
        run: |
          PASSWORD=$(openssl rand -base64 16)
          echo "RDP_PASS=$PASSWORD" >> $GITHUB_ENV
          
          sudo useradd -m -s /bin/bash rdpuser
          echo "rdpuser:$PASSWORD" | sudo chpasswd
          sudo usermod -aG sudo rdpuser

      - name: Configure xRDP for XFCE
        run: |
          echo "startxfce4" | sudo tee -a /home/rdpuser/.xsession
          sudo chown rdpuser:rdpuser /home/rdpuser/.xsession
          sudo systemctl restart xrdp

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-linux-rdp-${{ github.run_id }}

          TS_IP=$(tailscale ip -4 | head -n1)
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV

      - name: Verify RDP Accessibility
        run: |
          echo "Tailscale IP: $TAILSCALE_IP"
          nc -zv $TAILSCALE_IP 3389 || (echo "RDP not reachable" && exit 1)

      - name: Maintain Connection
        run: |
          echo "=== RDP ACCESS ==="
          echo "Host: $TAILSCALE_IP"
          echo "Username: rdpuser"
          echo "Password: $RDP_PASS"
          echo "=================="
          while true; do
            echo "[$(date)] RDP Active - Stop workflow to terminate"
            sleep 300
          done
